### ISSUE TITLE
Deploy fails w/ subscription id issues.

### ISSUE THREAD

**Issue by nikmd23** [lostintangent/azjs#20]
When I run `azjs deploy` from Windows, I get the browser based interactive login prompt, it appears to work fine, but then the following error prints out:

```bash
Error: The specified subscription ID isn't associated with your Azure account: 31ca0914-****-****-****-************
```

I don't see anything in the readme for addressing this, or how to specify a subscription id. I don't think this error string is coming from AzJs directly - at least I can't find it in the source - and I didn't see anything obvious in the `AzureClient` code.

**Comment by lostintangent** [comment]
Hmm, this might be a bug in [az-login](https://github.com/lostintangent/az-login), where it's auto-subscription detection logic fails. Couple of quick questions:

1. Do you have either of the following env vars set on your machine: `azureSubId` or `ARM_SUBSCRIPTION_ID`? If so, is the specified subscription associated with the account that you logged into after running `azjs deploy`?

2. Do you have `az` CLI installed on your machine? If so, are you logged into it with a difference Azure account than you used to authenticate with `azjs`?

The reason I ask is because `az-login` tries to infer your preferred subscription for deployments, by looking at env vars used by existing tools (E.g. Terraform, Serverless), as well as the default subscription configured with the `az` CLI, so it's possible that it attempts to use one of those settings, but the value is invalid due to there being an account mismatch.

If you don't have either of those settings configured (as expected for most new users), then it will either...

1. Auto-select the subscription, if the account you logged in with only has one
2. Display a prompt asking you which subscription you'd like to use, if the account you logged in with has multiple

I'm sure there are bugs in this behavior working correctly, so I'd love to figure out what's going wrong here.

**Comment by nikmd23** [comment]
> 1. Do you have either of the following env vars set on your machine: azureSubId or ARM_SUBSCRIPTION_ID? If so, is the specified subscription associated with the account that you logged into after running azjs deploy?

I do not.

> 2. Do you have az CLI installed on your machine? If so, are you logged into it with a difference Azure account than you used to authenticate with azjs?

I do. I'm not sure if I was logged in or not (it's been a long time since I used it), so I logged out to be sure.

After that I ran `azjs deploy`, and I got this new error, instead of the subscription error: `TypeError: Cannot read property 'id' of undefined`

**Comment by lostintangent** [comment]
@nikmd23 OK cool, thanks for confirming that. I think I see what the issue might be, so I'm going to submit a fix in a bit. Sorry for the inconvenience, but this is great feedback.

**Comment by nikmd23** [comment]
No worries at all. I'll keep on working though issues once I can get the app deployed. I know, I'm the PITA Windows user. ;)

**Comment by lostintangent** [comment]
@nikmd23 I believe this error should be resolved, and I published the fix to NPM. So if you could run `npm i -g azjs@latest` and then delete the `.azjs.json` file from your test app, that should get you into a good state again. Let me know if running `azjs deploy` gives you the same error.

**Comment by nikmd23** [comment]
I've upgraded to `0.1.13`, and I am now able to authenticate properly. 🙌 

I was prompted with an interactive subscription menu and everything. I'll close this issue. Thanks for your help @lostintangent.
